"""empty message

Revision ID: 08b116c74fb4
Revises: 971d6cb005c6
Create Date: 2024-07-02 10:47:28.099447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08b116c74fb4'
down_revision = '971d6cb005c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('masyarakat_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint('laporan_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'masyarakat', ['masyarakat_id'], ['user_id'])
        batch_op.drop_column('pelapor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pelapor_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('laporan_ibfk_2', 'masyarakat', ['pelapor_id'], ['user_id'])
        batch_op.drop_column('masyarakat_id')

    # ### end Alembic commands ###
