"""empty message

Revision ID: 43361d221856
Revises: d7e6d0360f8c
Create Date: 2024-06-29 18:22:23.728031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43361d221856'
down_revision = 'd7e6d0360f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sampah_disetor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sampah_disetor', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
