"""empty message

Revision ID: 4655d7388b0e
Revises: d52884d2f617
Create Date: 2024-07-02 11:18:35.516581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4655d7388b0e'
down_revision = 'd52884d2f617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_laporan', sa.DateTime(), nullable=True))
        batch_op.drop_column('laporan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laporan', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('tanggal_laporan')

    # ### end Alembic commands ###
