"""empty message

Revision ID: 47ee308b7e9d
Revises: 4655d7388b0e
Create Date: 2024-07-02 11:31:22.992365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47ee308b7e9d'
down_revision = '4655d7388b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sampah_disetor')
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('berat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('jenis_sampah', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('laporan_ibfk_1', type_='foreignkey')
        batch_op.drop_column('tps_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tps_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('laporan_ibfk_1', 'tps', ['tps_id'], ['id'])
        batch_op.drop_column('jenis_sampah')
        batch_op.drop_column('berat')
        batch_op.drop_column('foto')

    op.create_table('sampah_disetor',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('masyarakat_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('foto', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('berat', mysql.FLOAT(), nullable=False),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('jenis_sampah', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tanggal_setor', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['masyarakat_id'], ['masyarakat.user_id'], name='sampah_disetor_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
