"""Tambah atribut foto profil pada Petugas

Revision ID: 66de7a8e857e
Revises: b48a1ffc5648
Create Date: 2024-07-10 00:30:51.481903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66de7a8e857e'
down_revision = 'b48a1ffc5648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petugas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_profil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petugas', schema=None) as batch_op:
        batch_op.drop_column('foto_profil')

    # ### end Alembic commands ###
