"""remove jam operasional TPS

Revision ID: 68d250372840
Revises: 77ba6441a413
Create Date: 2024-07-14 11:29:51.455566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68d250372840'
down_revision = '77ba6441a413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.drop_column('jam_operasional_end')
        batch_op.drop_column('jam_operasional_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jam_operasional_start', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('jam_operasional_end', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
