"""empty message

Revision ID: 72e431c482b1
Revises: 
Create Date: 2024-07-09 22:40:10.586641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e431c482b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masyarakat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poin', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masyarakat', schema=None) as batch_op:
        batch_op.drop_column('poin')

    # ### end Alembic commands ###
