"""empty message

Revision ID: 758c1ad6d9df
Revises: 
Create Date: 2024-06-27 15:58:07.618428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '758c1ad6d9df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jam_operasional_start', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('jam_operasional_end', sa.String(length=100), nullable=True))
        batch_op.drop_column('jam_operasional')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jam_operasional', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('jam_operasional_end')
        batch_op.drop_column('jam_operasional_start')

    # ### end Alembic commands ###
