"""add foto attribute to TPS

Revision ID: 77ba6441a413
Revises: 032d343cbcff
Create Date: 2024-07-14 10:48:20.232116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ba6441a413'
down_revision = '032d343cbcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
