"""empty message

Revision ID: 7cdb21038a48
Revises: 94646b0c3396
Create Date: 2024-07-04 23:23:11.307780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdb21038a48'
down_revision = '94646b0c3396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masyarakat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_profil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masyarakat', schema=None) as batch_op:
        batch_op.drop_column('foto_profil')

    # ### end Alembic commands ###
