"""empty message

Revision ID: 94646b0c3396
Revises: 4fe038fb4958
Create Date: 2024-07-04 07:10:11.728828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94646b0c3396'
down_revision = '4fe038fb4958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tps_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'tps', ['tps_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tps_id')

    # ### end Alembic commands ###
