"""empty message

Revision ID: 96e7af6c846c
Revises: 47ee308b7e9d
Create Date: 2024-07-02 15:26:21.917205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e7af6c846c'
down_revision = '47ee308b7e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petugas_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'petugas', ['petugas_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('petugas_id')

    # ### end Alembic commands ###
