"""empty message

Revision ID: 971d6cb005c6
Revises: 
Create Date: 2024-07-02 10:23:58.918505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '971d6cb005c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pelapor_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('tps_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('laporan_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tps', ['tps_id'], ['id'])
        batch_op.create_foreign_key(None, 'masyarakat', ['pelapor_id'], ['user_id'])
        batch_op.drop_column('masyarakat_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('masyarakat_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('laporan_ibfk_1', 'masyarakat', ['masyarakat_id'], ['user_id'])
        batch_op.drop_column('status')
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')
        batch_op.drop_column('tps_id')
        batch_op.drop_column('pelapor_id')

    # ### end Alembic commands ###
