"""penambahan atribut poin pada model petugas

Revision ID: b48a1ffc5648
Revises: 72e431c482b1
Create Date: 2024-07-09 22:52:23.177730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48a1ffc5648'
down_revision = '72e431c482b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petugas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poin', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petugas', schema=None) as batch_op:
        batch_op.drop_column('poin')

    # ### end Alembic commands ###
