"""empty message

Revision ID: b6c563638598
Revises: 7cdb21038a48
Create Date: 2024-07-05 20:26:06.726127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c563638598'
down_revision = '7cdb21038a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petugas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_telepon', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petugas', schema=None) as batch_op:
        batch_op.drop_column('no_telepon')

    # ### end Alembic commands ###
