"""changing KlaimReward attribute

Revision ID: cbd13d66aca7
Revises: 68d250372840
Create Date: 2024-07-21 16:34:10.346396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbd13d66aca7'
down_revision = '68d250372840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint('riwayat_reward_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('masyarakat_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('masyarakat_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('riwayat_reward_ibfk_1', 'masyarakat', ['masyarakat_id'], ['user_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
