"""empty message

Revision ID: d7e6d0360f8c
Revises: dabb7bb64e64
Create Date: 2024-06-29 17:06:59.465173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e6d0360f8c'
down_revision = 'dabb7bb64e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sampah_disetor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sampah_disetor', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
